version: "3.9"

services:
  db:
    image: postgres:16-alpine
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    volumes:
      - ../config/postgresql.conf:/etc/postgresql/postgresql.conf
    env_file: ../../.env.test
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha_db
