name: Automated Testing
on:
  pull_request:
    branches:
      - main
      - develop
      - staging
      - "release/**"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Get NODE_VERSION from package.json
        id: node_version
        run: echo NODE_VERSION=$(node -pe node -pe "require('./package.json').engines.node") >> $GITHUB_OUTPUT
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
      - name: Install packages
        run: npm ci
      - name: Build server
        run: npm run build
      - name: Setting database
        run: npm run compose:test
      - name: Running tests
        run: npm run test
